namespace Cuddle.Core.Structs.Asset;

public enum ELegacyFileVersion {
    OLDEST_LOADABLE_PACKAGE = -2,

    CUSTOM_VERSION_ENUM = -2,
    CUSTOM_VERSION_GUID = -3,
    REMOVED_UE3_VERSION = -4,
    READDED_UE3_VERSION = -5,
    CUSTOM_VERSION_OPTIMIZED = -6,
    TEXTURE_ALLOC_REMOVED = -7,
    ADDED_UE5_VERSION = -8,

    NEWEST_LOADABLE_PACKAGE = ADDED_UE5_VERSION,
}
